### ISSUE TITLE
Can't Run Install.bat using esp-idf v4.2 Due to Expired Security Certificate

### ISSUE THREAD

**Issue by HowardHonig** [espressif/esp-va-sdk#157]
Trying the new esp-va-sdk v2.0.  Installed the recommended esp-idf v4.2.   When running the install.bat I get the below error(s).  Using Windows 10. I checked the site certificate using chrome and, indeed, the SSL certificate has expired.   The previously installed version of esp-idf 4.3  install.bat works.

I downloaded ninja-1.10.0-win64.zip and placed it in the .espressif/dist directory.  Then reran the install.bat file.  This seemed to work but at this point I don't know if this action is the correct one or will cause some other problem(s).  Even if it does work,  you should know the issue and update the certificate, I believe.

Skipping openocd-esp32@v0.10.0-esp32-20200709 (already installed)
Installing ninja@1.10.0
Downloading ninja-1.10.0-win64.zip to C:\Users\howar\.espressif\dist\ninja-1.10.0-win64.zip.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.0-win64.zip to C:\Users\howar\.espressif\dist\ninja-1.10.0-win64.zip.tmp
Downloading ninja-1.10.0-win64.zip to C:\Users\howar\.espressif\dist\ninja-1.10.0-win64.zip.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.0-win64.zip to C:\Users\howar\.espressif\dist\ninja-1.10.0-win64.zip.tmp
Downloading ninja-1.10.0-win64.zip to C:\Users\howar\.espressif\dist\ninja-1.10.0-win64.zip.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.0-win64.zip to C:\Users\howar\.espressif\dist\ninja-1.10.0-win64.zip.tmp
ERROR: Failed to download, and retry count has expired
Traceback (most recent call last):
  File "C:\Users\howar\AppData\Local\esp-idf\tools\idf_tools.py", line 1545, in <module>
    main(sys.argv[1:])
  File "C:\Users\howar\AppData\Local\esp-idf\tools\idf_tools.py", line 1541, in main
    action_func(args)
  File "C:\Users\howar\AppData\Local\esp-idf\tools\idf_tools.py", line 1218, in action_install
    tool_obj.download(tool_version)
  File "C:\Users\howar\AppData\Local\esp-idf\tools\idf_tools.py", line 601, in download
    raise DownloadError()
__main__.DownloadError

**Comment by chiragatal** [comment]
This was caused because of some certificates getting expired in esp-idf. We are already working on it. Once that change is merged and released on esp-idf, you can update idf, and this issue as well as https://github.com/espressif/esp-va-sdk/issues/158 should be fixed.
